name: procar.api

services:
  api:
    image: nandoburgos/procar.api
    container_name: procar.api
    environment:
      - PORT=4106
      - DATABASE_URL=mysql://boz:Ewhblt69%21%40%23@boz.app.br:3306/procar?connection_limit=20&socketTimeout=30
      - URL=https://api-procar.nandoburgos.dev
      - WEBSITE_URL=https://procar.nandoburgos.dev
      - JWT_SECRET=0IGSGJ0IWOsdljfo
      - SMTP_USER=get_from_github_secrets
      - SMTP_PASS=get_from_github_secrets
    ports:
      - "4106:4106"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

volumes:
  static_volume:
    name: "procar_static_files"